#!/bin/bash
# install.sh — Vault Assistant setup wizard
#
# Usage:
#   bash install.sh
#   bash install.sh --defaults   # use defaults where possible
#
# The script will:
#   1. Collect vault path and preferences
#   2. Create config.sh
#   3. Install Python dependencies
#   4. Optionally register cron jobs
#   5. Optionally register OpenCode skill

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BOLD='\033[1m'
GREEN='\033[92m'
YELLOW='\033[93m'
CYAN='\033[96m'
NC='\033[0m'

echo -e "${BOLD}${CYAN}"
echo "╔══════════════════════════════════════╗"
echo "║     Obsidian Vault Assistant Setup   ║"
echo "╚══════════════════════════════════════╝"
echo -e "${NC}"

# ===== 1. Vault path =====
echo -e "${BOLD}Obsidian Vault${NC}"
echo "Path to your Obsidian vault (where daily/, weekly/, _logs/ live)."
echo -n "Vault path [$HOME/Documents/Obsidian/MyVault]: "
read -r VAULT_INPUT
VAULT_DIR="${VAULT_INPUT:-$HOME/Documents/Obsidian/MyVault}"
VAULT_DIR="${VAULT_DIR/#\~/$HOME}"

while [ ! -d "$VAULT_DIR" ]; do
  echo -e "${YELLOW}Directory does not exist: $VAULT_DIR${NC}"
  echo -n "Enter a valid vault path (or 'skip' to create later): "
  read -r VAULT_INPUT
  if [ "$VAULT_INPUT" = "skip" ]; then
    echo "Creating directory..."
    mkdir -p "$VAULT_DIR"
    break
  fi
  VAULT_DIR="${VAULT_INPUT/#\~/$HOME}"
done
echo -e "  ${GREEN}✓${NC} Vault: $VAULT_DIR"

# Create essential vault dirs
mkdir -p "$VAULT_DIR"/{daily,weekly} "$VAULT_DIR"/_logs/{kpi,trends} 2>/dev/null
echo -e "  ${GREEN}✓${NC} Created: daily, weekly, _logs/{kpi,trends}"

# ===== 2. GitHub owner (optional) =====
echo ""
echo -e "${BOLD}GitHub Integration${NC} (optional)"
echo "Used by vault-status.sh and weekly_fill.py for blocked/next issue tracking."
echo "Searches ALL repos under this GitHub username/org."
echo "Requires 'gh' CLI to be installed and authenticated."
echo -n "GitHub username (e.g. 'your-username' or press Enter to skip): "
read -r GH_OWNER_INPUT
GH_OWNER="${GH_OWNER_INPUT:-}"
if [ -n "$GH_OWNER" ]; then
  echo -e "  ${GREEN}✓${NC} GitHub owner: $GH_OWNER"
else
  echo -e "  ${YELLOW}⚠${NC} Skipped (no GitHub integration)"
fi

# ===== 3. Cron schedules =====
echo ""
echo -e "${BOLD}Cron Schedule${NC}"
echo "Daily cron: collects KPI data every morning."
echo -n "Time (HH:MM, 24h format) [$DEFAULT_DAILY_TIME]: "
DEFAULT_DAILY_TIME="06:00"
read -r DAILY_TIME_INPUT
DAILY_TIME="${DAILY_TIME_INPUT:-$DEFAULT_DAILY_TIME}"
DAILY_HOUR="${DAILY_TIME%%:*}"
DAILY_MIN="${DAILY_TIME##*:}"
echo -e "  ${GREEN}✓${NC} Daily: $DAILY_TIME"

echo "Weekly cron: generates weekly review on Monday."
echo -n "Time (HH:MM, 24h format) [$DEFAULT_WEEKLY_TIME]: "
DEFAULT_WEEKLY_TIME="07:00"
read -r WEEKLY_TIME_INPUT
WEEKLY_TIME="${WEEKLY_TIME_INPUT:-$DEFAULT_WEEKLY_TIME}"
WEEKLY_HOUR="${WEEKLY_TIME%%:*}"
WEEKLY_MIN="${WEEKLY_TIME##*:}"
echo -e "  ${GREEN}✓${NC} Weekly: $WEEKLY_TIME (Monday)"

# ===== 4. Write config.sh =====
cat > "$SCRIPT_DIR/config.sh" <<CONFIGEOF
#!/bin/bash
# config.sh — Generated by install.sh
# Source: config.example.sh

VAULT_DIR="$VAULT_DIR"
SCRIPTS_DIR="$SCRIPT_DIR/scripts"
LOG_DIR="$VAULT_DIR/_logs"
KPI_DIR="$VAULT_DIR/_logs/kpi"
TREND_DIR="$VAULT_DIR/_logs/trends"
DAILY_CRON_TIME="${DAILY_MIN} ${DAILY_HOUR} * * *"
WEEKLY_CRON_TIME="${WEEKLY_MIN} ${WEEKLY_HOUR} * * 1"
CONFIGEOF

if [ -n "$GH_OWNER" ]; then
  echo "GH_OWNER=\"$GH_OWNER\"" >> "$SCRIPT_DIR/config.sh"
fi

echo -e "\n  ${GREEN}✓${NC} Created: config.sh"

# ===== 5. Install Python deps =====
echo ""
echo -e "${BOLD}Python Dependencies${NC}"
if [ -f "$SCRIPT_DIR/scripts/requirements.txt" ]; then
  echo "Core scripts use stdlib only — no extra deps needed."
  echo "Optional: install google-api-python-client for calendar sync."
  echo -n "Install optional deps? [y/N]: "
  read -r INSTALL_DEPS
  if [[ "$INSTALL_DEPS" =~ ^[Yy] ]]; then
    python3 -m pip install -r "$SCRIPT_DIR/scripts/requirements.txt" 2>&1
    echo -e "  ${GREEN}✓${NC} Optional deps installed"
  fi
else
  echo "Core scripts use stdlib only — no extra deps needed."
fi

# ===== 6. Cron setup =====
echo ""
echo -e "${BOLD}Cron Jobs${NC}"
echo "This will add entries to your crontab."
echo -n "Setup cron jobs? [Y/n]: "
read -r SETUP_CRON
if [[ ! "$SETUP_CRON" =~ ^[Nn] ]]; then
  CRON_CMD_DAILY="${DAILY_MIN} ${DAILY_HOUR} * * * $SCRIPT_DIR/scripts/daily-cron.sh"
  CRON_CMD_WEEKLY="${WEEKLY_MIN} ${WEEKLY_HOUR} * * 1 $SCRIPT_DIR/scripts/weekly-cron.sh"

  # Check if entries already exist
  (crontab -l 2>/dev/null || true) | grep -v "daily-cron.sh\|weekly-cron.sh" > /tmp/crontab_new
  echo "$CRON_CMD_DAILY" >> /tmp/crontab_new
  echo "$CRON_CMD_WEEKLY" >> /tmp/crontab_new
  crontab /tmp/crontab_new
  rm -f /tmp/crontab_new
  echo -e "  ${GREEN}✓${NC} Cron jobs added:"
  echo "    $CRON_CMD_DAILY"
  echo "    $CRON_CMD_WEEKLY"
else
  echo -e "  ${YELLOW}⚠${NC} Cron setup skipped"
fi

# ===== 7. OpenCode skill registration =====
echo ""
echo -e "${BOLD}OpenCode Skill${NC}"
echo "Register the vault assistant skill in OpenCode for proactive AI behavior."
echo -n "Register skill? [Y/n]: "
read -r REGISTER_SKILL
if [[ ! "$REGISTER_SKILL" =~ ^[Nn] ]]; then
  SKILL_DIR="$SCRIPT_DIR/skill"
  if [ -d "$SKILL_DIR" ]; then
    # Check if opencode.json exists
    OPENCODE_CONFIG="${OPENCODE_CONFIG:-$HOME/.config/opencode/opencode.json}"
    if [ -f "$OPENCODE_CONFIG" ]; then
      echo "  To register, add this to your opencode.json skill_triggers:"
      echo ""
      echo '    "vault": ['
      echo '      "vault",'
      echo '      "obsidian",'
      echo '      "daily note",'
      echo '      "weekly review",'
      echo '      "kpi",'
      echo '      "daily-cron"'
      echo '    ]'
      echo ""
      echo "  And add to skills.paths:"
      echo '    "'$SKILL_DIR'"'
      echo ""
      echo -e "  ${YELLOW}⚠${NC} Manual step needed — edit $OPENCODE_CONFIG"
    else
      echo "  SKILL.md and SKILL.md available at: $SKILL_DIR"
    fi
    echo -e "  ${GREEN}✓${NC} Skill directory ready"
  else
    echo -e "  ${YELLOW}⚠${NC} Skill directory not found: $SKILL_DIR"
  fi
fi

# ===== 8. GitHub auth check =====
if [ -n "$GH_OWNER" ]; then
  echo ""
  echo -e "${BOLD}GitHub Auth${NC}"
  if command -v gh &>/dev/null; then
    if gh auth status 2>&1 | grep -q "Logged in"; then
      echo -e "  ${GREEN}✓${NC} GitHub CLI authenticated"
    else
      echo -e "  ${YELLOW}⚠${NC} Run 'gh auth login' to enable issue tracking"
    fi
  else
    echo -e "  ${YELLOW}⚠${NC} GitHub CLI not installed. Install: https://cli.github.com/"
  fi
fi

# ===== Done =====
echo ""
echo -e "${BOLD}${GREEN}Setup Complete!${NC}"
echo ""
echo "What's next:"
echo "  1. Review config: $SCRIPT_DIR/config.sh"
echo "  2. Run status check: bash $SCRIPT_DIR/scripts/vault-status.sh --summary"
echo "  3. Generate weekly review: bash $SCRIPT_DIR/scripts/weekly_fill.py --force"
echo "  4. For OpenCode integration, add AGENTS.md to your vault root:"
echo "     https://github.com/your-username/obsidian-vault-assistant#opencode-integration"
echo ""
echo "Need help? Open an issue on GitHub."
